# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:7.17.12@sha256:3de705b1689f77b4c7b9c60cf2aaf861e6b48e377279bde9b100b31d38419f2d

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
