version: "3.8"
services:

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - my_network
    ports:
      - "669:80"
    volumes:
      - ./static:/etc/nginx/html:ro
      - ./nginx:/etc/nginx/conf.d


  prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: prometheus-exporter
    networks:
      - my_network
    environment:
      - SCRAPE_URI=http://nginx:669/nginx_status
    ports:
      - "9113:9113"
    depends_on:
      - prometheus


  prometheus:
    image: prom/prometheus
    container_name: prometheus 
    networks:
      - my_network
    volumes:   
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - my_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana

networks:
  my_network:
    driver: bridge