# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.12@sha256:1d32aaee1673c45dba5ed666ae167ed3e5010ec1b5a20ee782197b66092749ab

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
